version: '3'
services:
  backend:
    build: ../backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env.test
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: micro_kiosk
    ports:
      - "5432:5432"
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql