version: '3'
services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
